import Card from "../common/card";

function EfficientFrontierChart({ points = [] }) {
  const width = 860;
  const height = 320;
  const padding = 44;

  if (!points.length) {
    return (
      <Card
        title="Efficient frontier chart"
        subtitle="Risk-return visualization for frontier portfolios."
      >
        <div
          style={{
            minHeight: 220,
            display: "grid",
            placeItems: "center",
            color: "var(--text-muted)",
            textAlign: "center",
          }}
        >
          Run the efficient frontier workflow to render the frontier chart.
        </div>
      </Card>
    );
  }

  const volatilities = points.map((point) => point.volatility);
  const returns = points.map((point) => point.expected_return);

  const minX = Math.min(...volatilities);
  const maxX = Math.max(...volatilities);
  const minY = Math.min(...returns);
  const maxY = Math.max(...returns);

  function scaleX(value) {
    if (maxX === minX) {
      return padding + (width - padding * 2) / 2;
    }

    return (
      padding +
      ((value - minX) / (maxX - minX)) * (width - padding * 2)
    );
  }

  function scaleY(value) {
    if (maxY === minY) {
      return height / 2;
    }

    return (
      height -
      padding -
      ((value - minY) / (maxY - minY)) * (height - padding * 2)
    );
  }

  const plottedPoints = points.map((point) => ({
    ...point,
    x: scaleX(point.volatility),
    y: scaleY(point.expected_return),
  }));

  const polylinePoints = plottedPoints
    .map((point) => `${point.x},${point.y}`)
    .join(" ");

  return (
    <Card
      title="Efficient frontier chart"
      subtitle="Risk-return visualization for portfolios generated by the optimization engine."
    >
      <div style={{ overflowX: "auto" }}>
        <svg
          viewBox={`0 0 ${width} ${height}`}
          width="100%"
          height="320"
          role="img"
          aria-label="Efficient frontier chart"
        >
          <line
            x1={padding}
            y1={height - padding}
            x2={width - padding}
            y2={height - padding}
            stroke="rgba(148, 163, 184, 0.35)"
            strokeWidth="1.5"
          />
          <line
            x1={padding}
            y1={padding}
            x2={padding}
            y2={height - padding}
            stroke="rgba(148, 163, 184, 0.35)"
            strokeWidth="1.5"
          />

          <polyline
            fill="none"
            stroke="url(#frontierGradient)"
            strokeWidth="3"
            points={polylinePoints}
          />

          {plottedPoints.map((point, index) => (
            <g key={`${point.expected_return}-${point.volatility}-${index}`}>
              <circle
                cx={point.x}
                cy={point.y}
                r="5.5"
                fill="#38bdf8"
                stroke="rgba(255,255,255,0.85)"
                strokeWidth="1.2"
              />
              <title>
                {`Point ${index + 1}: Return ${point.expected_return.toFixed(
                  4
                )}, Volatility ${point.volatility.toFixed(4)}`}
              </title>
            </g>
          ))}

          <text
            x={width / 2}
            y={height - 8}
            textAnchor="middle"
            fill="var(--text-faint)"
            fontSize="12"
          >
            Volatility (risk)
          </text>

          <text
            x="14"
            y={height / 2}
            transform={`rotate(-90 14 ${height / 2})`}
            textAnchor="middle"
            fill="var(--text-faint)"
            fontSize="12"
          >
            Expected return
          </text>

          <defs>
            <linearGradient
              id="frontierGradient"
              x1="0%"
              y1="0%"
              x2="100%"
              y2="0%"
            >
              <stop offset="0%" stopColor="#22c55e" />
              <stop offset="100%" stopColor="#38bdf8" />
            </linearGradient>
          </defs>
        </svg>
      </div>

      <div
        style={{
          marginTop: 12,
          display: "flex",
          flexWrap: "wrap",
          gap: 18,
          color: "var(--text-muted)",
          fontSize: "0.92rem",
        }}
      >
        <span>Min volatility: {minX.toFixed(4)}</span>
        <span>Max volatility: {maxX.toFixed(4)}</span>
        <span>Min return: {minY.toFixed(4)}</span>
        <span>Max return: {maxY.toFixed(4)}</span>
      </div>
    </Card>
  );
}

export default EfficientFrontierChart;